# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# A workflow to automatically backport pull requests to a stable branch.
#
# This workflow uses the Backport CLI (https://github.com/sorenlouv/backport)
# under the hood, which is configured in `.backportrc.json` in the repository
# root.
#
# See https://github.com/sorenlouv/backport-github-action for documentation
# on the used action.

name: Backport PRs to stable branches

on:
  pull_request_target:
    # Run this workflow when a label on a PR is added, or if it's closed.
    types: ["labeled", "closed"]

jobs:
  backport-create:
    name: Backport PR
    # Also update branchLabelMapping in .backportrc.json when changing the label
    # here.
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'backport-to:')
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        uses: sorenlouv/backport-github-action@v9.5.1
        with:
          # GITHUB_TOKEN is available by default, but the powers it has are
          # configurable. Follow the GitHub documentation at
          # https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository
          # to "Allow GitHub Actions to create and approve pull requests".
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log

      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log
